[package]
name = "zarrs-ffi"
description = "FFI bindings for the zarrs crate"
version = "0.4.1"
authors = ["Lachlan Deakin <ljdgit@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/LDeakin/zarrs-ffi"
keywords = ["zarr"]
categories = ["encoding"]

[lib]
name = "zarrs_ffi"
crate-type = ["staticlib", "cdylib"]

[dev-dependencies]
inline-c = "0.1.7"

[build-dependencies]
cbindgen = "0.26"

[dependencies]
derive_more = "0.99.17"
ffi-support = "0.4.4"
once_cell = "1.18.0"
serde_json = { version = "1.0.105", features = ["preserve_order"] }
tempdir = "0.3.7"
zarrs = { version = "0.12.0" }

# [patch.crates-io]
# zarrs = { path = "../zarrs" }
