name: artifacts

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  x86_64-unknown-linux-gnu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update && sudo apt install -y cmake clang-15
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup target add x86_64-unknown-linux-gnu
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --release --features cbindgen --features zarrs/zfp,zarrs/bitround --target x86_64-unknown-linux-gnu
      - name: package
        run: |
          mkdir include lib &&
          cp zarrs.h include/ &&
          cp target/x86_64-unknown-linux-gnu/release/libzarrs* lib/ &&
          tar czvf zarrs-ffi-x86_64-unknown-linux-gnu.tar.gz README.md CHANGELOG.md include/zarrs.h lib/libzarrs.a lib/libzarrs.so
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zarrs-ffi-x86_64-unknown-linux-gnu
          path: zarrs-ffi-x86_64-unknown-linux-gnu.tar.gz
